version: '3.7'

services:
  aligno-server:
    container_name: aligno-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1337:1337
    environment:
      - CHOKIDAR_USEPOLLING=true
