name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: docker stop alignoweb
      - run: docker rm alignoweb
      - run: docker rmi alignoweb_alignoweb:latest
      - run: npm i
      #- run: npm install @fontsource/source-sans-pro
      #- run: npm install @fontsource/league-spartan
      - run: npm run build --if-present
      - run: docker-compose up -d --build
